services:
  # 🟩 API Service
  - type: web
    name: saleor-api
    env: docker
    image: ghcr.io/saleor/saleor:3.22
    envVars:
      - key: DATABASE_URL
        value: postgres://<SUPABASE_USER>:<SUPABASE_PASSWORD>@<SUPABASE_HOST>:5432/<SUPABASE_DB>
      - key: REDIS_URL
        value: redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DASHBOARD_URL
        value: https://saleor-dashboard.onrender.com/
    healthCheckPath: /graphql/

  # 🟨 Celery Worker (renamed type)
  - type: worker
    name: saleor-worker
    env: docker
    image: ghcr.io/saleor/saleor:3.22
    dockerCommand: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    envVars:
      - key: DATABASE_URL
        value: postgres://<SUPABASE_USER>:<SUPABASE_PASSWORD>@<SUPABASE_HOST>:5432/<SUPABASE_DB>
      - key: REDIS_URL
        value: redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
      - key: SECRET_KEY
        sync: saleor-api:SECRET_KEY

  # 🟦 Dashboard (React Admin UI)
  - type: web
    name: saleor-dashboard
    env: static
    buildCommand: ""
    staticPublishPath: /
    image: ghcr.io/saleor/saleor-dashboard:latest
    envVars:
      - key: API_URI
        value: https://saleor-api.onrender.com/graphql/

