# render.yaml — Deploy Saleor 3.22 with Supabase and Render Redis

services:
  # 🟩 Saleor API (GraphQL backend)
  - type: web
    name: saleor-api
    env: docker
    image: ghcr.io/saleor/saleor:3.22
    plan: starter
    healthCheckPath: /graphql/
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DASHBOARD_URL
        value: https://saleor-dashboard.onrender.com/
      - key: DEFAULT_FROM_EMAIL
        value: saleor@example.com
      - key: EMAIL_URL
        value: smtp://user:pass@smtp.example.com:587

  # 🟨 Celery Worker
  - type: worker
    name: saleor-worker
    env: docker
    image: ghcr.io/saleor/saleor:3.22
    dockerCommand: >
      celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    envVars:
      - key: DATABASE_URL
        sync: saleor-api:DATABASE_URL
      - key: REDIS_URL
        sync: saleor-api:REDIS_URL
      - key: SECRET_KEY
        sync: saleor-api:SECRET_KEY

  # 🟦 Saleor Dashboard (React admin)
  - type: web
    name: saleor-dashboard
    env: static
    image: ghcr.io/saleor/saleor-dashboard:latest
    staticPublishPath: /
    buildCommand: ""
    envVars:
      - key: API_URI
        value: https://saleor-api.onrender.com/graphql/
